#!/bin/sh

# ====================================
# Install packages
# ====================================

read -p 'Install virtualbox additions? (y/N): ' choice

if [ "$choice" = "y" ]; then
    sudo pacman -S xf86-video-vmware virtualbox-guest-utils virtualbox-guest-modules-arch --noconfirm --needed
fi

sudo pacman -S curl xorg xorg-xinit feh rofi ranger bspwm sxhkd dunst vim neofetch python3 zsh noto-fonts noto-fonts-emoji ttf-font-awesome otf-font-awesome pulseaudio pulseaudio-alsa pamixer unzip picom wget make --noconfirm --needed

if pacman -Qs yay > /dev/null ; then
    echo "Yay is already installed, moving on..."
else
    rm -rf yay
    git clone https://aur.archlinux.org/yay.git
    cd yay
    makepkg -si --noconfirm
fi

# Import Keys to Install Spotify

gpg --keyserver pool.sks-keyservers.net --recv-keys 931FF8E79F0876134EDDBDCCA87FF9DF48BF1C90
gpg --keyserver pool.sks-keyservers.net --recv-keys 2EBF997C15BDA244B6EBF5D84773BD5E130D1D45

yay -S polybar rxvt-unicode-256xresources spicetify-cli nerd-fonts-iosevka python-ueberzug spotify betterlockscreen --needed --removemake --nocleanmenu --nodiffmenu --noeditmenu --noconfirm

# ====================================
# Polybar font
# ====================================

mkdir ~/.local &> /dev/null
mkdir ~/.local/share &> /dev/null
mkdir ~/.local/share/fonts &> /dev/null
curl https://raw.githubusercontent.com/adi1090x/polybar-themes/master/polybar-8/fonts/icomoon-feather.ttf > icomoon-feather.ttf
mv icomoon-feather.ttf ~/.local/share/fonts/
fc-cache -vf ~/.local/share/fonts/

# ====================================
# Powerline arrow fix
# ====================================

wget https://github.com/powerline/powerline/raw/develop/font/PowerlineSymbols.otf
mv PowerlineSymbols.otf ~/.local/share/fonts/
fc-cache -vf ~/.local/share/fonts/

# Make pacman display colored output
sudo sed -i 's/#Color/Color/g' /etc/pacman.conf

# =========================================
# Install antigen and zsh-autosuggestions
# =========================================

if [ -d "$HOME/.antigen" ]; then
    echo "Antigen is already installed, moving on..."
else
    mkdir $HOME/.antigen
    curl -L git.io/antigen > $HOME/.antigen/antigen.zsh
fi

sudo pacman -S broot exa --noconfirm --needed

echo "=============="
echo "==== DONE ===="
echo "=============="
echo "$ chsh -s /bin/zsh"
echo "$ startx"
echo "$ feh --bg-fill ~/.config/desktop/gruvbox.png"

# Change to zsh
zsh