code --install-extension asciidoctor.asciidoctor-vscode
code --install-extension bierner.color-info
code --install-extension christian-kohler.npm-intellisense
code --install-extension DavidAnson.vscode-markdownlint
code --install-extension dbaeumer.vscode-eslint
code --install-extension dlasagno.wal-theme
code --install-extension eamodio.gitlens
code --install-extension equinusocio.vsc-material-theme-icons
code --install-extension esbenp.prettier-vscode
code --install-extension GitHub.github-vscode-theme
code --install-extension hashicorp.terraform
code --install-extension haskell.haskell
code --install-extension hoovercj.haskell-linter
code --install-extension justusadam.language-haskell
code --install-extension mathiasfrohlich.Kotlin
code --install-extension mosbasik.sxhkdrc-syntax
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-kubernetes-tools.vscode-kubernetes-tools
code --install-extension ms-python.python
code --install-extension ms-python.vscode-pylance
code --install-extension ms-toolsai.jupyter
code --install-extension ms-toolsai.jupyter-keymap
code --install-extension ms-toolsai.jupyter-renderers
code --install-extension ms-toolsai.vscode-jupyter-cell-tags
code --install-extension ms-toolsai.vscode-jupyter-slideshow
code --install-extension ms-vscode-remote.remote-containers
code --install-extension ms-vscode.sublime-keybindings
code --install-extension pnp.polacode
code --install-extension redhat.vscode-yaml
code --install-extension scala-lang.scala
code --install-extension scalameta.metals
code --install-extension vscjava.vscode-gradle
code --install-extension vscode-icons-team.vscode-icons
code --install-extension vscodevim.vim
code --install-extension webrender.synthwave-x-fluoromachine
code --install-extension willi84.vikings-icon-theme
code --install-extension XadillaX.viml
code --install-extension yoyo.D3Snippets