code --install-extension asciidoctor.asciidoctor-vscode
code --install-extension bierner.color-info
code --install-extension christian-kohler.npm-intellisense
code --install-extension DavidAnson.vscode-markdownlint
code --install-extension dbaeumer.vscode-eslint
code --install-extension eamodio.gitlens
code --install-extension EditorConfig.EditorConfig
code --install-extension equinusocio.vsc-material-theme-icons
code --install-extension esbenp.prettier-vscode
code --install-extension GitHub.github-vscode-theme
code --install-extension GitHub.vscode-pull-request-github
code --install-extension imjacobclark.vscode-lisp-formatter
code --install-extension iocave.customize-ui
code --install-extension iocave.monkey-patch
code --install-extension janisdd.vscode-edit-csv
code --install-extension jolaleye.horizon-theme-vscode
code --install-extension mosbasik.sxhkdrc-syntax
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-kubernetes-tools.vscode-kubernetes-tools
code --install-extension ms-vscode.sublime-keybindings
code --install-extension msjsdiag.debugger-for-chrome
code --install-extension pnp.polacode
code --install-extension redhat.vscode-yaml
code --install-extension scala-lang.scala
code --install-extension scalameta.metals
code --install-extension vscodevim.vim
code --install-extension webrender.synthwave-x-fluoromachine
code --install-extension willi84.vikings-icon-theme
code --install-extension XadillaX.viml
code --install-extension yoyo.D3Snippets
