#! /bin/sh

killall -q variety &
sxhkd &

. $HOME/Scripts/setscreen.sh

if [[ "${EXTERNAL_MONITOR}" != "" ]]; then
    bspc monitor ${EXTERNAL_MONITOR} -d 1 2 3 4 5
    bspc monitor ${NORMAL_MONITOR}  -d 6 7 8 9 10

    xrandr \
        --output ${EXTERNAL_MONITOR} --mode 1920x1080 --rotate normal --primary \
        --output ${NORMAL_MONITOR}  --mode 1366x768  --rotate normal --right-of ${EXTERNAL_MONITOR}
else
    bspc monitor ${NORMAL_MONITOR} -d 1 2 3 4 5

    xrandr \
        --output ${NORMAL_MONITOR}  --mode 1366x768  --rotate normal --primary
fi

wmname LG3D

# for mon in `bspc query -M`; do
#     bspc config -m $mon right_padding 0
#     bspc config -m $mon bottom_padding 0
#     bspc config -m $mon left_padding 0
#     bspc config -m $mon top_padding 0
# done

## Rules

#bspc rule -a Org.gnome.Nautilus state=floating
bspc rule -a Terminator sticky=on state=floating rectangle=widthxheight+Xoffset+Yoffset
bspc rule -a Screenkey manage=off

## Config
bspc config border_width         2
bspc config border_radius        12
bspc config window_gap           5

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config history_aware_focus  true

bspc config focused_border_color "#E60053"
bspc config normal_border_color "#00A5AF"

# --------------------------------
# ------- Non-BSPWM related ------
# --------------------------------
# Set wallpaper
feh --bg-fill ~/.config/desktop/wallpapers/wallhaven-eydedl.jpg
# Reload .Xresources
xrdb -load ~/.Xresources
# Launch polybar
~/.config/polybar/launch.sh
# Change from ugly 'X' cursor when hovering over background
xsetroot -cursor_name left_ptr
# Make betterlockscreen generate and cache a background image for locking
betterlockscreen -u ~/.config/desktop/wallpapers/LockWallpaper.png
# betterlockscreen -u ~/Documents/Wallpapers/gruvbox.png

# ------- Autostart apps ------
# Picom
picom --xrender-sync-fence &

# Dunst
dunst &

# Network manager applet
nm-applet &

# Wallpaper Rotation
# runs variety && `variety &`
variety &

# ------- Mouse/Touchpad fixes ------
# Start libinput gestures
# libinput-gestures-setup start

# Xinput configs (touchpad)
# xinput set-prop "DLL07BE:01 06CB:7A13 Touchpad" "libinput Natural Scrolling Enabled" 1
# xinput set-prop "DLL07BE:01 06CB:7A13 Touchpad" "libinput Click Method Enabled" 0 1
# xinput set-prop "DLL07BE:01 06CB:7A13 Touchpad" "libinput Disable While Typing Enabled" 0

# ------- Keyboard fixes ------
# Remap Caps-lock key to Escape, for using VIM
setxkbmap -option caps:escape
# Make US and DK keyboard layout togglable with Shift+Alt
setxkbmap -layout us -variant intl option grp:alt_shift_toggle
