#! /bin/sh

# background
killall -q variety &

# key bindings
sxhkd &

. ~/.local/bin/setscreens

if [[ "${EXTERNAL_MONITOR}" != "" ]]; then
    bspc monitor ${EXTERNAL_MONITOR} -d 1 2 3 4 5
    bspc monitor ${NORMAL_MONITOR}  -d 6 7 8 9 10

    xrandr \
        --output ${EXTERNAL_MONITOR} --mode 1920x1080 --rotate normal --primary \
        --output ${NORMAL_MONITOR}  --mode 1366x768  --rotate normal --right-of ${EXTERNAL_MONITOR}
else
    bspc monitor ${NORMAL_MONITOR} -d 1 2 3 4 5

    xrandr \
        --output ${NORMAL_MONITOR}  --mode 1366x768  --rotate normal --primary
fi

wmname LG3D

# for mon in `bspc query -M`; do
#     bspc config -m $mon right_padding 0
#     bspc config -m $mon bottom_padding 0
#     bspc config -m $mon left_padding 0
#     bspc config -m $mon top_padding 0
# done

## Rules
bspc rule -a feh state='floating'
bspc rule -a openssh-askpass state='floating'
bspc rule -a URxvt:scratchy sticky=on state=floating rectangle=widthxheight+Xoffset+Yoffset
bspc rule -a Screenkey manage=off
bspc rule -a Zathura state=tiled
bspc rule -a Pavucontrol state='floating'
bspc rule -a flameshot state='floating'
bspc rule -a *:SPLASH state=floating
bspc desktop -f 1

## Config
bspc config border_width         0
# bspc config border_radius        12
bspc config window_gap           5

bspc config top_padding 30
bspc config right_padding 0
bspc config bottom_padding 0
bspc config left_padding 0

bspc config split_ratio          0.5
bspc config borderless_monocle   false
bspc config gapless_monocle      true
bspc config paddingless_monocle  true

bspc config pointer_modifier      mod1
bspc config click_to_focus        true
bspc config focus_follows_pointer false
bspc config pointer_action1       move
bspc config pointer_action2       resize_side
bspc config pointer_action3       resize_corner

bspc config history_aware_focus  true

# Source Pywal Colors
. ${HOME}/.cache/wal/colors.sh

bspc config normal_border_color  "$color1"
bspc config active_border_color   "$color2"
bspc config focused_border_color "$color15"

# Use if bspwm >= 0.9.4
bspc config presel_feedback_color "$color1"

# --------------------------------
# ------- Non-BSPWM related ------
# --------------------------------

# Set wallpaper
feh --bg-fill ~/.config/desktop/wallpapers/wallhaven-3zz9xv.png

# unclutter (hides mouse while typing)
unclutter -idle 2 &

# start redshift
# redshift -t 6500:5200 -l geoclue2 &

# Reload .Xresources
xrdb -load ~/.Xresources

# Launch polybar
~/.config/polybar/launch.sh --shapes > ~/.config/polybar/logs/polybar.log 2>&1 &

# Change from ugly 'X' cursor when hovering over background
xsetroot -cursor_name left_ptr

# Make betterlockscreen generate and cache a background image for locking
betterlockscreen -u ~/.config/desktop/wallpapers/LockWallpaper.png

# ------- Autostart apps ------
# Picom
picom --xrender-sync-fence &

# Dunst
dunst &

# Network manager applet
nm-applet &

# Wallpaper Rotation
# runs variety && `variety &`
variety &

# ------- Mouse/Touchpad fixes ------
# Start libinput gestures
# libinput-gestures-setup start

# Xinput configs (touchpad)
# xinput set-prop "DLL07BE:01 06CB:7A13 Touchpad" "libinput Natural Scrolling Enabled" 1
# xinput set-prop "DLL07BE:01 06CB:7A13 Touchpad" "libinput Click Method Enabled" 0 1
# xinput set-prop "DLL07BE:01 06CB:7A13 Touchpad" "libinput Disable While Typing Enabled" 0

# ------- Keyboard fixes ------
# Remap Caps-lock key to Escape, for using VIM
# setxkbmap -option caps:escape
setxkbmap -option caps:capslock

# Make US and ES keyboard layout togglable with Shift+Alt
# setxkbmap -layout us -variant intl option grp:alt_shift_toggle
setxkbmap -model pc105 -layout es,us -variant ,intl option grp:alt_shift_toggle

export _JAVA_AWT_WM_NONREPARENTING=1
